name: Deploy to Fly.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js (for backend)
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Build frontend
        run: |
          cd back
          npm run build-frontend

      - name: Set up Fly.io CLI
        uses: fly-apps/flyctl-actions@v1
        with:
          flyctl_version: "latest"

      - name: Deploy to Fly.io
        run: |
          flyctl deploy --config back/fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
